apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-push-quarkuscoffeeshop-homeoffice-backend
  namespace: quarkuscoffeeshop-cicd
  labels:
    app: quarkuscoffeeshop-homeoffice-backend
spec:
  params:
    - default: latest
      description: Image Tag Value
      name: IMAGE_TAG
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: 'https://github.com/nmushino/quarkuscoffeeshop-homeoffice-backend'
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: maven-run
      params:
        - name: CONTEXT_DIR
          value: .
        - name: GOALS
          value:
            - clean
            - package
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
#    - name: build-java-app-image
#      params:
#        - name: CONTEXT
#          value: /workspace/source
#        - name: DOCKERFILE
#          value: /workspace/source/src/main/docker/Dockerfile.jvm
#        - name: IMAGE
#          value: >-
#            image-registry.openshift-image-registry.svc:5000/quarkuscoffeeshop-demo/quarkuscoffeeshop-homeoffice-backend:$(params.IMAGE_TAG)
#      runAfter:
#        - maven-run
#      taskRef:
#        kind: ClusterTask
#        name: buildah
#      workspaces:
#        - name: source
#          workspace: shared-workspace
    - name: push-oc-apps
      params:
        - name: SCRIPT
          value: |
            oc delete all -l app=homeoffice-backend -n quarkuscoffeeshop-demo || true
            oc delete bc/homeoffice-backend -n quarkuscoffeeshop-demo || true
            oc new-build --binary --name=homeoffice-backend --image-stream=java:17 -n quarkuscoffeeshop-demo
            oc start-build homeoffice-backend --from-dir=target/quarkus-app/ --follow -n quarkuscoffeeshop-demo
            oc new-app homeoffice-backend --name=homeoffice-backend --allow-missing-images -n quarkuscoffeeshop-demo
            oc set env deployment/homeoffice-backend JAVA_OPTS_APPEND="-Dquarkus.profile=prod" -n quarkuscoffeeshop-demo

            PGSQL_URL=$(oc get configmap coffeeshop-config -n quarkuscoffeeshop-demo -o=jsonpath='{.data.PGSQL_URL}')
            oc set env deployment/homeoffice-backend PGSQL_URL=$PGSQL_URL -n quarkuscoffeeshop-demo
            PGSQL_USER=$(oc get secret coffeeshopdb-pguser-coffeeshopadmin -n quarkuscoffeeshop-demo -o=jsonpath='{.data.user}' | base64 --decode)
            oc set env deployment/homeoffice-backend PGSQL_USER=$PGSQL_USER -n quarkuscoffeeshop-demo
            PGSQL_PASS=$(oc get secret coffeeshopdb-pguser-coffeeshopadmin -n quarkuscoffeeshop-demo -o=jsonpath='{.data.password}' | base64 --decode)
            oc set env deployment/homeoffice-backend PGSQL_PASS=$PGSQL_PASS -n quarkuscoffeeshop-demo

            oc expose deployment homeoffice-backend --port=8080 --name=homeoffice-backend -n quarkuscoffeeshop-demo
            oc expose svc homeoffice-backend --name=homeoffice-backend -n quarkuscoffeeshop-demo

      runAfter:
        - maven-run
      taskRef:
        name: push-app-task
      workspaces:
        - name: source
          workspace: shared-workspace
  workspaces:
  - name: shared-workspace
  - name: maven-settings