apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-push-quarkuscoffeeshop-barista
  namespace: quarkuscoffeeshop-cicd
  labels:
    app: quarkuscoffeeshop-barista
spec:
  params:
    - default: latest
      description: Image Tag Value
      name: IMAGE_TAG
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: 'https://github.com/nmushino/quarkuscoffeeshop-barista'
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: maven-run
      params:
        - name: CONTEXT_DIR
          value: .
        - name: GOALS
          value:
            - clean
            - package
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
    - name: build-java-app-image
      params:
        - name: CONTEXT
          value: /workspace/source
        - name: DOCKERFILE
          value: /workspace/source/src/main/docker/Dockerfile.jvm
        - name: IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/quarkuscoffeeshop-demo/quarkuscoffeeshop-barista:$(params.IMAGE_TAG)
      runAfter:
        - maven-run
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: push-oc-apps
      taskRef:
        name: push-image-task
      params:
        - name: SCRIPT
          value: |
            oc delete all -l app=barista -n quarkuscoffeeshop-demo
            oc new-build --binary --name=barista -n quarkuscoffeeshop-demo
            oc start-build barista --from-file=target/quarkuscoffeeshop-barista-5.1.0.jar --follow -n quarkuscoffeeshop-demo
            #oc apply -f openshift/coffeeshop-sub-configmap.yaml
            #oc apply -f openshift/barista-development.yaml -n quarkuscoffeeshop-demo
      runAfter:
        - build-java-app-image
      workspaces:
        - name: source
          workspace: shared-workspace
  workspaces:
  - name: shared-workspace
  - name: maven-settings