apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: quarkuscoffeeshop-inventory-git
  labels:
    app: quarkuscoffeeshop-inventory
spec:
  type: git
  params:
  - name: url
    value: https://github.com/quarkuscoffeeshop/quarkuscoffeeshop-inventory
  - name: revision
    value: 5.0.0-SNAPSHOT
