apiVersion: v1
kind: ConfigMap
metadata:
  name: coffeeshop-config
  namespace: quarkuscoffeeshop-demo
data:
  KAFKA_BOOTSTRAP_URLS: "cafe-cluster-kafka-bootstrap:9092"
  STREAM_URL: "http://localhost:8080/dashboard/stream"
  LOYALTY_STREAM_URL: "http://localhost:8080/dashboard/loyaltystream"
  CORS_ORIGINS: "http://localhost:8080"
  STORE_ID: "TOKYO"
  PGSQL_URL: "jdbc:postgresql://coffeeshopdb-ha:5432/coffeeshopdb?currentSchema=coffeeshop"
  QUARKUS_LOG_LEVEL: "INFO"
  QUARKUSCOFFEESHOP_LOG_LEVEL: "INFO"