apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: quarkuscoffeeshop-web-git
  labels:
    app: quarkuscoffeeshop-web
spec:
  type: git
  params:
  - name: url
    value: https://github.com/quarkuscoffeeshop/quarkuscoffeeshop-web
  - name: revision
    value: 5.0.3-SNAPSHOT
