apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - quarkuscoffeeshop-counter-deployment.yaml
  - quarkuscoffeeshop-counter-service.yaml
transformers:
- ./transformer-patches.yaml