apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-push-quarkusdroneshop-web
  namespace: quarkusdroneshop-cicd
  labels:
    app: quarkusdroneshop-web
spec:
  params:
    - default: latest
      description: Image Tag Value
      name: IMAGE_TAG
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: 'https://github.com/quarkusdroneshop/quarkusdroneshop-web'
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: maven-run
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: maven-no-settings17
      params:
        - name: CONTEXT_DIR
          value: .
        - name: GOALS
          value: "clean package"
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: push-oc-apps
      runAfter:
        - maven-run
      taskRef:
        name: push-app-task
      params:
        - name: SCRIPT
          value: |
            #!/bin/bash
            set -e

            oc delete all -l app=web -n quarkusdroneshop-demo || true
            oc delete bc/web -n quarkusdroneshop-demo || true
            oc new-build --binary --name=web --image-stream=java:openjdk-11-ubi8 -n quarkusdroneshop-demo
            oc start-build web --from-dir=target/quarkus-app/ --follow -n quarkusdroneshop-demo
            oc new-app web --name=web --allow-missing-images -n quarkusdroneshop-demo
            oc set env deployment/web JAVA_OPTS_APPEND="-Dquarkus.profile=prod" -n quarkusdroneshop-demo
            oc expose deployment web --port=8080 --name=quarkusdroneshop-web -n quarkusdroneshop-demo
            oc expose svc quarkusdroneshop-web --name=quarkusdroneshop-web -n quarkusdroneshop-demo

            CONFIG_CORS_ORIGINS=$(oc get route quarkusdroneshop-web -o jsonpath='{.spec.host}' -n quarkusdroneshop-demo)
            CONFIG_LOYALTY_STREAM_URL=$(oc get route quarkusdroneshop-web -o jsonpath='{.spec.host}' -n quarkusdroneshop-demo)/dashboard/loyaltystream
            CONFIG_STREAM_URL=$(oc get route quarkusdroneshop-web -o jsonpath='{.spec.host}' -n quarkusdroneshop-demo)/dashboard/stream
            CONFIG_REWARD_STREAM_URL=$(oc get route quarkusdroneshop-web -o jsonpath='{.spec.host}' -n quarkusdroneshop-demo)/dashboard/rewards/stream
            oc patch configmap droneshop-config -n quarkusdroneshop-demo -p "{\"data\":{\"CORS_ORIGINS\":\"http://$CONFIG_CORS_ORIGINS\"}}"
            oc patch configmap droneshop-config -n quarkusdroneshop-demo -p "{\"data\":{\"LOYALTY_STREAM_URL\":\"http://$CONFIG_LOYALTY_STREAM_URL\"}}"
            oc patch configmap droneshop-config -n quarkusdroneshop-demo -p "{\"data\":{\"STREAM_URL\":\"http://$CONFIG_STREAM_URL\"}}"
            oc patch configmap droneshop-config -n quarkusdroneshop-demo -p "{\"data\":{\"REWARD_STREAM_URL\":\"http://$CONFIG_REWARD_STREAM_URL\"}}"

            KAFKA_URL=$(oc get configmap droneshop-config -n quarkusdroneshop-demo -o=jsonpath='{.data.KAFKA_BOOTSTRAP_URLS}')
            oc set env deployment/web KAFKA_BOOTSTRAP_URLS=$KAFKA_URL -n quarkusdroneshop-demo

            STREAM_URL=$(oc get configmap droneshop-config -n quarkusdroneshop-demo -o=jsonpath='{.data.STREAM_URL}')
            oc set env deployment/web STREAM_URL=$STREAM_URL -n quarkusdroneshop-demo
            LOYALTY_STREAM_URL=$(oc get configmap droneshop-config -n quarkusdroneshop-demo -o=jsonpath='{.data.LOYALTY_STREAM_URL}')
            oc set env deployment/web LOYALTY_STREAM_URL=$LOYALTY_STREAM_URL -n quarkusdroneshop-demo
            CORS_ORIGINS=$(oc get configmap droneshop-config -n quarkusdroneshop-demo -o=jsonpath='{.data.CORS_ORIGINS}')
            oc set env deployment/web CORS_ORIGINS=$CORS_ORIGINS -n quarkusdroneshop-demo
            STORE_ID=$(oc get configmap droneshop-config -n quarkusdroneshop-demo -o=jsonpath='{.data.STORE_ID}')
            oc set env deployment/web STORE_ID=$STORE_ID -n quarkusdroneshop-demo
            REWARD_STREAM_URL=$(oc get configmap droneshop-config -n quarkusdroneshop-demo -o=jsonpath='{.data.REWARD_STREAM_URL}')
            oc set env deployment/web REWARD_STREAM_URL=$REWARD_STREAM_URL -n quarkusdroneshop-demo
      workspaces:
        - name: source
          workspace: shared-workspace