apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeoffice-pipeline-cache
  namespace: quarkuscoffeeshop-cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
