apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkuscoffeeshop-barista
spec:
  destination:
    name: ''
    namespace: quarkuscoffeeshop-cicd
    server: 'https://kubernetes.default.svc'
  source:
    path: quarkuscoffeeshop-barista
    repoURL: >-
      https://github.com/quarkuscoffeeshop/tekton-pipelines.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
