apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quarkusdroneshop-maven-settings-pvc
  namespace: quarkusdroneshop-cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
