apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - quarkuscoffeeshop-inventory-deployment.yaml
  - quarkuscoffeeshop-inventory-service.yaml
transformers:
- ./transformer-patches.yaml