kind: Service
apiVersion: v1
metadata:
  name: quarkuscoffeeshop-barista
  namespace: quarkuscoffeeshop-demo
  labels:
    app: quarkuscoffeeshop-barista
spec:
  ports:
    - name: 8778-tcp
      protocol: TCP
      port: 8778
      targetPort: 8778
    - name: 9779-tcp
      protocol: TCP
      port: 9779
      targetPort: 9779
  selector:
    app: quarkuscoffeeshop-barista
  type: ClusterIP
  sessionAffinity: None