apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkuscoffeeshop-counter
spec:
  destination:
    name: ''
    namespace: quarkuscoffeeshop-cicd
    server: 'https://kubernetes.default.svc'
  source:
    path: quarkuscoffeeshop-counter
    repoURL: >-
      https://github.com/quarkuscoffeeshop/tekton-pipelines.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
