apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkusdroneshop-counter
spec:
  destination:
    name: ''
    namespace: quarkusdroneshop-cicd
    server: 'https://kubernetes.default.svc'
  source:
    path: quarkusdroneshop-counter
    repoURL: %REPO_NAME%
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
