---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../common-functions
  
resources:
  - resources/coffeeshop-configmap.yaml
  - pvc/pvc.yml
  - pvc/maven-source-pvc.yml
  - pipeline/deploy-pipeline.yaml
