---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../common-functions
- ../application-deployment/homeoffice/quarkuscoffeeshop-homeoffice-ui

resources:
  - tektontasks/pushImageToQuay.yaml
  - resources/git-pipeline-resource.yaml
  - resources/image-pipeline-resource.yaml
  - pipeline/deploy-pipeline.yaml

