---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../common-functions
- ../application-deployment/homeoffice/quarkuscoffeeshop-homeoffice-ui

resources:
  - pvc/pvc.yml
  - tektontasks/pushImageToQuay.yaml
  - tektontasks/s2i-nodejs-task.yaml
  - resources/git-pipeline-resource.yaml
  - resources/image-pipeline-resource.yaml
  - pipeline/deploy-pipeline.yaml

