apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-push-quarkusdroneshop-qdca10
  namespace: quarkusdroneshop-cicd
  labels:
    app: quarkusdroneshop-qdca10
spec:
  params:
    - default: latest
      description: Image Tag Value
      name: IMAGE_TAG
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: 'https://github.com/nmushino/quarkusdroneshop-qdca10'
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: maven-run
      params:
        - name: CONTEXT_DIR
          value: .
        - name: GOALS
          value:
            - clean
            - package
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
#    - name: build-java-app-image
#      params:
#        - name: CONTEXT
#          value: /workspace/source
#        - name: DOCKERFILE
#          value: /workspace/source/src/main/docker/Dockerfile.jvm
#        - name: IMAGE
#          value: >-
#            image-registry.openshift-image-registry.svc:5000/quarkusdroneshop-demo/quarkusdroneshop-qdca10:$(params.IMAGE_TAG)
#      runAfter:
#        - maven-run
#      taskRef:
#        kind: ClusterTask
#        name: buildah
#      workspaces:
#        - name: source
#          workspace: shared-workspace
    - name: push-oc-apps
      params:
        - name: SCRIPT
          value: |
            #!/bin/bash
            set -e

            oc delete all -l app=qdca10 -n quarkusdroneshop-demo || true
            oc delete bc/qdca10 -n quarkusdroneshop-demo || true
            oc new-build --binary --name=qdca10 --image-stream=java:openjdk-11-ubi8 -n quarkusdroneshop-demo
            oc start-build qdca10 --from-dir=target/quarkus-app/ --follow -n quarkusdroneshop-demo
            oc new-app qdca10 --name=qdca10 --allow-missing-images -n quarkusdroneshop-demo
            oc set env deployment/qdca10 JAVA_OPTS_APPEND="-Dquarkus.profile=prod" -n quarkusdroneshop-demo
            
            KAFKA_URL=$(oc get configmap droneshop-config -n quarkusdroneshop-demo -o=jsonpath='{.data.KAFKA_BOOTSTRAP_URLS}')
            oc set env deployment/qdca10 KAFKA_BOOTSTRAP_URLS=$KAFKA_URL -n quarkusdroneshop-demo
            QUARKUS_LOG_LEVEL=$(oc get configmap droneshop-config -n quarkusdroneshop-demo -o=jsonpath='{.data.QUARKUS_LOG_LEVEL}')
            oc set env deployment/qdca10 QUARKUS_LOG_LEVEL=$QUARKUS_LOG_LEVEL -n quarkusdroneshop-demo
            QUARKUSCOFFEESHOP_LOG_LEVEL=$(oc get configmap droneshop-config -n quarkusdroneshop-demo -o=jsonpath='{.data.QUARKUSCOFFEESHOP_LOG_LEVEL}')
            oc set env deployment/qdca10 QUARKUSCOFFEESHOP_LOG_LEVEL=$QUARKUSCOFFEESHOP_LOG_LEVEL -n quarkusdroneshop-demo
      runAfter:
        - maven-run
      taskRef:
        name: push-app-task
      workspaces:
        - name: source
          workspace: shared-workspace
  workspaces:
  - name: shared-workspace
  - name: maven-settings