apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-and-push-quarkuscoffeeshop-homeoffice-ui
  labels:
    app: quarkuscoffeeshop-homeoffice-ui
spec:
  params:
    - default: quay-auth-secret
      name: quay-io-account
      type: string
    - default: >-
        http://quarkuscoffeeshop-homeoffice-ui-quarkuscoffeeshop-homeoffice.apps.shop.example.com/graphql
      description: The home office backend endpoint
      name: REACT_APP_GRAPHQL_ENDPOINT
      type: string
    - default: quay.io/quarkuscoffeeshop/quarkuscoffeeshop-homeoffice-ui
      name: quay-io-repository
      type: string
    - default: latest
      name: quay-io-image-tag-name
      type: string
    - default: latest
      description: Image Tag Value
      name: IMAGE_TAG
      type: string
    - default: webhook-secret
      description: Webhook secert name
      name: webhook-secret
      type: string
  resources:
    - name: app-git
      type: git
    - name: image
      type: image
  tasks:
    - name: build-nodejsapp
      params:
        - name: TLSVERIFY
          value: 'false'
        - name: IMAGE_TAG
          value: $(params.IMAGE_TAG)
        - name: REACT_APP_GRAPHQL_ENDPOINT
          value: $(params.REACT_APP_GRAPHQL_ENDPOINT)
      resources:
        inputs:
          - name: source
            resource: app-git
        outputs:
          - name: image
            resource: image
      taskRef:
        kind: Task
        name: s2i-nodejs
    - name: tag-test-image
      params:
        - name: SCRIPT
          value: |
            oc tag quarkuscoffeeshop-homeoffice-ui:$(params.IMAGE_TAG) quarkuscoffeeshop-homeoffice-ui:latest
      runAfter:
        - build-nodejsapp
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: push-to-test-env
      params:
        - name: SCRIPT
          value: |
            oc patch deployment/quarkuscoffeeshop-homeoffice-ui  --patch='{"spec":{"template":{"spec":{"containers":[{"name":"quarkuscoffeeshop-homeoffice-ui","image":"image-registry.openshift-image-registry.svc:5000/quarkuscoffeeshop-cicd/quarkuscoffeeshop-homeoffice-ui:'$(params.IMAGE_TAG)'"}]}}}}' -n quarkuscoffeeshop-homeoffice
      runAfter:
        - tag-test-image
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: push-image-to-quay
      params:
        - name: quay-io-repository
          value: $(params.quay-io-repository)
        - name: quay-io-image-tag-name
          value: $(params.quay-io-image-tag-name)
      resources:
        inputs:
          - name: image
            resource: image
      runAfter:
        - push-to-test-env
      taskRef:
        kind: Task
        name: push-image-to-quay