apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-push-quarkuscoffeeshop-homeoffice-ui
  namespace: quarkuscoffeeshop-cicd
  labels:
    app: quarkuscoffeeshop-homeoffice-ui
spec:
  params:
    - default: latest
      description: Image Tag Value
      name: IMAGE_TAG
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: 'https://github.com/nmushino/quarkuscoffeeshop-homeoffice-ui'
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
#    - name: maven-run
#      params:
#        - name: CONTEXT_DIR
#          value: .
#        - name: GOALS
#          value:
#            - clean
#            - package
#      runAfter:
#        - fetch-repository
#      taskRef:
#        kind: Task
#        name: maven
#      workspaces:
#        - name: maven-settings
#          workspace: maven-settings
#        - name: source
#          workspace: shared-workspace
#    - name: build-java-app-image
#      params:
#        - name: CONTEXT
#          value: /workspace/source
#        - name: DOCKERFILE
#          value: /workspace/source/src/main/docker/Dockerfile.jvm
#        - name: IMAGE
#          value: >-
#            image-registry.openshift-image-registry.svc:5000/quarkuscoffeeshop-demo/quarkuscoffeeshop-homeoffice-backend:$(params.IMAGE_TAG)
#      runAfter:
#        - maven-run
#      taskRef:
#        kind: ClusterTask
#        name: buildah
#      workspaces:
#        - name: source
#          workspace: shared-workspace
    - name: push-oc-apps
      params:
        - name: SCRIPT
          value: |
            #!/bin/bash
            set -e

            oc delete all -l app=homeoffice-ui -n quarkuscoffeeshop-demo || true
            oc delete bc/homeoffice-ui -n quarkuscoffeeshop-demo || true
            oc delete istag homeoffice-ui:latest -n quarkuscoffeeshop-demo || true

            echo "legacy-peer-deps=true" > .npmrc
            oc new-build --binary --name=homeoffice-ui --image-stream=openshift/nodejs -n quarkuscoffeeshop-demo
            oc start-build homeoffice-ui --from-dir=. --follow -n quarkuscoffeeshop-demo
            oc new-app homeoffice-ui --name=homeoffice-ui --allow-missing-images -n quarkuscoffeeshop-demo
            oc expose svc homeoffice-ui --name=homeoffice-ui -n quarkuscoffeeshop-demo || true

            CONFIG_REST_URL=$(oc get configmap coffeeshop-config -n quarkuscoffeeshop-demo -o=jsonpath='{.data.GRAHQL_URL}')
            CONFIG_ALLOWED_ORIGINS=$(oc get route homeoffice-ui -o jsonpath='{.spec.host}' -n quarkuscoffeeshop-demo)
            touch .env
            echo "REACT_APP_GRAPHQL_ENDPOINT=$CONFIG_REST_URL" >> .env
            echo "ALLOWED_ORIGINS=http://$CONFIG_ALLOWED_ORIGINS" >> .env

            oc set env deployment/homeoffice-ui CONFIG_REST_URL=$CONFIG_REST_URL -n quarkuscoffeeshop-demo
            oc set env deployment/homeoffice-ui CONFIG_ALLOWED_ORIGINS=$CONFIG_ALLOWED_ORIGINS -n quarkuscoffeeshop-demo

            oc patch deployment homeoffice-ui -n quarkuscoffeeshop-demo --type=json -p='[
              {
                "op": "add",
                "path": "/spec/template/spec/containers/0/securityContext",
                "value": {
                  "allowPrivilegeEscalation": false,
                  "capabilities": {
                    "drop": ["ALL"]
                  },
                  "runAsNonRoot": true
                }
              },
              {
                "op": "add",
                "path": "/spec/template/spec/securityContext",
                "value": {
                  "seccompProfile": {
                    "type": "RuntimeDefault"
                  }
                }
              }
            ]'
            oc rollout restart deployment/homeoffice-ui -n quarkuscoffeeshop-demo

      runAfter:
        - fetch-repository
      taskRef:
        name: push-app-task
      workspaces:
        - name: source
          workspace: shared-workspace
  workspaces:
  - name: shared-workspace
  - name: maven-settings
---
apiVersion: v1
kind: Service
metadata:
  name: homeoffice-ui
spec:
  selector:
    app: homeoffice-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # アプリが使用しているポートに合わせて調整