apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeoffice-backend-shared-workspace-pvc
  namespace: quarkusdroneshop-cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
