apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-push-quarkuscoffeeshop-web
  namespace: quarkuscoffeeshop-cicd
  labels:
    app: quarkuscoffeeshop-web
spec:
  params:
    - default: latest
      description: Image Tag Value
      name: IMAGE_TAG
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: 'https://github.com/nmushino/quarkuscoffeeshop-web'
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: maven-run
      params:
        - name: CONTEXT_DIR
          value: .
        - name: GOALS
          value:
            - clean
            - package
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
#    - name: build-java-app-image
#      params:
#        - name: CONTEXT
#          value: /workspace/source
#        - name: DOCKERFILE
#          value: /workspace/source/src/main/docker/Dockerfile.jvm
#        - name: IMAGE
#          value: >-
#            image-registry.openshift-image-registry.svc:5000/quarkuscoffeeshop-demo/quarkuscoffeeshop-web:$(params.IMAGE_TAG)
#      runAfter:
#        - maven-run
#      taskRef:
#        kind: ClusterTask
#        name: buildah
#      workspaces:
#        - name: source
#          workspace: shared-workspace
    - name: push-oc-apps
      params:
        - name: SCRIPT
          value: |
            oc delete all -l app=web -n quarkuscoffeeshop-demo || true
            oc delete bc/web -n quarkuscoffeeshop-demo || true
            oc new-build --binary --name=web --image-stream=java:11 -n quarkuscoffeeshop-demo
            oc start-build web --from-dir=target/quarkus-app/ --follow -n quarkuscoffeeshop-demo
            oc new-app web --name=web --allow-missing-images -n quarkuscoffeeshop-demo
            oc set env deployment/web JAVA_OPTS_APPEND="-Dquarkus.profile=prod" -n quarkuscoffeeshop-demo
            oc expose deployment web --port=8080 --name=quarkuscoffeeshop-web -n quarkuscoffeeshop-demo
            oc expose svc quarkuscoffeeshop-web --name=quarkuscoffeeshop-web -n quarkuscoffeeshop-demo

            KAFKA_URL=$(oc get configmap coffeeshop-config -n quarkuscoffeeshop-demo -o=jsonpath='{.data.KAFKA_BOOTSTRAP_URLS}')
            oc set env deployment/counter KAFKA_BOOTSTRAP_URLS=$KAFKA_URL -n quarkuscoffeeshop-demo

            STREAM_URL=$(oc get configmap coffeeshop-config -n quarkuscoffeeshop-demo -o=jsonpath='{.data.STREAM_URL}')
            oc set env deployment/counter STREAM_URL=$STREAM_URL -n quarkuscoffeeshop-demo
            LOYALTY_STREAM_URL=$(oc get configmap coffeeshop-config -n quarkuscoffeeshop-demo -o=jsonpath='{.data.LOYALTY_STREAM_URL}')
            oc set env deployment/counter LOYALTY_STREAM_URL=$LOYALTY_STREAM_URL -n quarkuscoffeeshop-demo
            CORS_ORIGINS:=$(oc get configmap coffeeshop-config -n quarkuscoffeeshop-demo -o=jsonpath='{.data.CORS_ORIGINS:}')
            oc set env deployment/counter CORS_ORIGINS:=$CORS_ORIGINS: -n quarkuscoffeeshop-demo
            STORE_ID:=$(oc get configmap coffeeshop-config -n quarkuscoffeeshop-demo -o=jsonpath='{.data.STORE_ID:}')
            oc set env deployment/counter STORE_ID:=$STORE_ID: -n quarkuscoffeeshop-demo
      runAfter:
        - maven-run
      taskRef:
        name: push-app-task
      workspaces:
        - name: source
          workspace: shared-workspace
  workspaces:
  - name: shared-workspace
  - name: maven-settings