apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-push-quarkusdroneshop-homeoffice-ui
  namespace: quarkusdroneshop-cicd
  labels:
    app: quarkusdroneshop-homeoffice-ui
spec:
  params:
    - default: latest
      description: Image Tag Value
      name: IMAGE_TAG
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: 'https://github.com/nmushino/quarkusdroneshop-homeoffice-ui'
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
#    - name: maven-run
#      params:
#        - name: CONTEXT_DIR
#          value: .
#        - name: GOALS
#          value:
#            - clean
#            - package
#      runAfter:
#        - fetch-repository
#      taskRef:
#        kind: Task
#        name: maven
#      workspaces:
#        - name: maven-settings
#          workspace: maven-settings
#        - name: source
#          workspace: shared-workspace
#    - name: build-java-app-image
#      params:
#        - name: CONTEXT
#          value: /workspace/source
#        - name: DOCKERFILE
#          value: /workspace/source/src/main/docker/Dockerfile.jvm
#        - name: IMAGE
#          value: >-
#            image-registry.openshift-image-registry.svc:5000/quarkusdroneshop-demo/quarkusdroneshop-homeoffice-backend:$(params.IMAGE_TAG)
#      runAfter:
#        - maven-run
#      taskRef:
#        kind: ClusterTask
#        name: buildah
#      workspaces:
#        - name: source
#          workspace: shared-workspace
    - name: push-oc-apps
      params:
        - name: SCRIPT
          value: |
            #!/bin/bash
            set -e

            oc delete route homeoffice-ui -n quarkusdroneshop-demo || true
            oc delete svc homeoffice-ui -n quarkusdroneshop-demo || true
            oc delete deployment homeoffice-ui -n quarkusdroneshop-demo || true
            oc delete is homeoffice-ui -n quarkusdroneshop-demo || true
            oc delete bc/homeoffice-ui -n quarkusdroneshop-demo || true
            oc delete istag homeoffice-ui:latest -n quarkusdroneshop-demo || true

            echo "legacy-peer-deps=true" > .npmrc
            ./set-endpoint.sh
            oc new-build --binary --name=homeoffice-ui --image-stream=openshift/nodejs:18-ubi8 -n quarkusdroneshop-demo
            oc start-build homeoffice-ui --from-dir=. --follow -n quarkusdroneshop-demo
            oc new-app homeoffice-ui --name=homeoffice-ui --allow-missing-images -n quarkusdroneshop-demo
            oc expose svc homeoffice-ui --name=homeoffice-ui -n quarkusdroneshop-demo || true

            oc annotate deployment -l app=homeoffice-ui app.openshift.io/connects-to='["homeoffice-backend"]' -n quarkusdroneshop-demo
            oc annotate deployment -l app=homeoffice-backend app.openshift.io/connects-to='["postgres"]' -n quarkusdroneshop-demo
            oc label dc -l app=postgres app.kubernetes.io/name=postgresql -n quarkusdroneshop-demo
            oc label deployment -l app=homeoffice-backend app.kubernetes.io/name=quarkus -n quarkusdroneshop-demo
            oc label deployment -l app=homeoffice-ui app.kubernetes.io/name=nodejs -n quarkusdroneshop-demo

            oc patch deployment homeoffice-ui -n quarkusdroneshop-demo --type=json -p='[
              {
                "op": "add",
                "path": "/spec/template/spec/containers/0/securityContext",
                "value": {
                  "allowPrivilegeEscalation": false,
                  "capabilities": {
                    "drop": ["ALL"]
                  },
                  "runAsNonRoot": true
                }
              },
              {
                "op": "add",
                "path": "/spec/template/spec/securityContext",
                "value": {
                  "seccompProfile": {
                    "type": "RuntimeDefault"
                  }
                }
              }
            ]'

      runAfter:
        - fetch-repository
      taskRef:
        name: push-app-task
      workspaces:
        - name: source
          workspace: shared-workspace
  workspaces:
  - name: shared-workspace
  - name: maven-settings
---
apiVersion: v1
kind: Service
metadata:
  name: homeoffice-ui
spec:
  selector:
    app: homeoffice-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # アプリが使用しているポートに合わせて調整