apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - quarkuscoffeeshop-web-deployment.yaml
  - quarkuscoffeeshop-web-service.yaml
  - quarkuscoffeeshop-web-route.yaml
transformers:
- ./transformer-patches.yaml