apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - quarkuscoffeeshop-kitchen-deployment.yaml
  - quarkuscoffeeshop-kitchen-service.yaml
transformers:
- ./transformer-patches.yaml