kind: Service
apiVersion: v1
metadata:
  name: quarkuscoffeeshop-kitchen
  namespace: quarkuscoffeeshop-demo
  labels:
    app: quarkuscoffeeshop-kitchen
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: quarkuscoffeeshop-kitchen
  type: ClusterIP
  sessionAffinity: None