apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkusdroneshop-homeoffice-ui
spec:
  destination:
    name: ''
    namespace: quarkusdroneshop-cicd
    server: 'https://kubernetes.default.svc'
  source:
    path: quarkusdroneshop-homeoffice-ui
    repoURL: %REPO_NAME%
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
