apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-push-quarkuscoffeeshop-kitchen
  namespace: quarkuscoffeeshop-cicd
  labels:
    app: quarkuscoffeeshop-kitchen
spec:
  params:
    - default: latest
      description: Image Tag Value
      name: IMAGE_TAG
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: 'https://github.com/nmushino/quarkuscoffeeshop-kitchen'
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: maven-run
      params:
        - name: CONTEXT_DIR
          value: .
        - name: GOALS
          value:
            - clean
            - package
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
#    - name: build-java-app-image
#      params:
#        - name: CONTEXT
#          value: /workspace/source
#        - name: DOCKERFILE
#          value: /workspace/source/src/main/docker/Dockerfile.jvm
#        - name: IMAGE
#          value: >-
#            image-registry.openshift-image-registry.svc:5000/quarkuscoffeeshop-demo/quarkuscoffeeshop-kitchen:$(params.IMAGE_TAG)
#      runAfter:
#        - maven-run
#      taskRef:
#        kind: ClusterTask
#        name: buildah
#      workspaces:
#        - name: source
#          workspace: shared-workspace
    - name: push-oc-apps
      params:
        - name: SCRIPT
          value: |
            #!/bin/bash
            set -e

            oc delete all -l app=kitchen -n quarkuscoffeeshop-demo || true
            oc delete bc/kitchen -n quarkuscoffeeshop-demo || true
            oc new-build --binary --name=kitchen --image-stream=java:openjdk-11-ubi8 -n quarkuscoffeeshop-demo
            oc start-build kitchen --from-dir=target/quarkus-app/ --follow -n quarkuscoffeeshop-demo
            oc new-app kitchen --name=kitchen --allow-missing-images -n quarkuscoffeeshop-demo
            oc set env deployment/kitchen JAVA_OPTS_APPEND="-Dquarkus.profile=prod" -n quarkuscoffeeshop-demo
            
            KAFKA_URL=$(oc get configmap coffeeshop-config -n quarkuscoffeeshop-demo -o=jsonpath='{.data.KAFKA_BOOTSTRAP_URLS}')
            oc set env deployment/kitchen KAFKA_BOOTSTRAP_URLS=$KAFKA_URL -n quarkuscoffeeshop-demo
            QUARKUS_LOG_LEVEL=$(oc get configmap coffeeshop-config -n quarkuscoffeeshop-demo -o=jsonpath='{.data.QUARKUS_LOG_LEVEL}')
            oc set env deployment/kitchen QUARKUS_LOG_LEVEL=$QUARKUS_LOG_LEVEL -n quarkuscoffeeshop-demo
            QUARKUSCOFFEESHOP_LOG_LEVEL=$(oc get configmap coffeeshop-config -n quarkuscoffeeshop-demo -o=jsonpath='{.data.QUARKUSCOFFEESHOP_LOG_LEVEL}')
            oc set env deployment/kitchen QUARKUSCOFFEESHOP_LOG_LEVEL=$QUARKUSCOFFEESHOP_LOG_LEVEL -n quarkuscoffeeshop-demo
      runAfter:
        - maven-run
      taskRef:
        name: push-app-task
      workspaces:
        - name: source
          workspace: shared-workspace
  workspaces:
  - name: shared-workspace
  - name: maven-settings