apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slack-webhook
  namespace: quarkusdroneshop-cicd
spec:
  destination:
    namespace: quarkusdroneshop-cicd
    server: 'https://kubernetes.default.svc'
  project: quarkusdroneshop-majestic-monolith-1
  source:
    path: event-notification/
    repoURL: >-
      http://gogs-quarkusdroneshop-cicd.apps.ocp4.example.com/user1/tekton-pipelines.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true