apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkusdroneshop-edge-pipeline
  namespace: quarkusdroneshop-cicd
spec:
  destination:
    namespace: quarkusdroneshop-cicd
    server: 'https://kubernetes.default.svc'
  project: quarkusdroneshop-majestic-monolith-1
  source:
    path: quarkusdroneshop-majestic-monolith
    repoURL: %REPO_NAME%
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true