apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: quarkusdroneshop-majestic-monolith-1
  namespace: quarkusdroneshop-cicd
spec:
  description: ArgoCD project for quarkusdroneshop-majestic-monolith (EDGE)
  destinations:
    - namespace: quarkusdroneshop-cicd
      server: 'https://kubernetes.default.svc'
    - namespace: quarkusdroneshop-integration
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - >-
      http://gogs-quarkusdroneshop-cicd.apps.ocp4.example.com/user1/tekton-pipelines.git
