apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-push-quarkuscoffeeshop-customermocker
  labels:
    app: quarkuscoffeeshop-customermocker
  namespace: quarkuscoffeeshop-cicd
spec:
  params:
    - default: latest
      description: Image Tag Value
      name: IMAGE_TAG
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: 'https://github.com/nmushino/quarkuscoffeeshop-customermocker'
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: maven-run
      params:
        - name: CONTEXT_DIR
          value: .
        - name: GOALS
          value:
            - clean
            - package
        - name: MAVEN_IMAGE
          value: maven:3.8.5-openjdk-11
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
#    - name: build-java-app-image
#      params:
#        - name: CONTEXT
#          value: /workspace/source
#        - name: DOCKERFILE
#          value: /workspace/source/src/main/docker/Dockerfile.jvm
#        - name: IMAGE
#          value: >-
#            image-registry.openshift-image-registry.svc:5000/quarkuscoffeeshop-demo/quarkuscoffeeshop-counter:$(params.IMAGE_TAG)
#      runAfter:
#        - maven-run
#      taskRef:
#        kind: ClusterTask
#        name: buildah
#      workspaces:
#        - name: source
#          workspace: shared-workspace
    - name: push-oc-apps
      params:
        - name: SCRIPT
          value: |
            #!/bin/bash
            set -e

            oc delete all -l app=customermocker -n quarkuscoffeeshop-demo || true
            oc delete bc/customermocker -n quarkuscoffeeshop-demo || true
            oc new-build --binary --name=customermocker --image-stream=java:openjdk-11-ubi8 -n quarkuscoffeeshop-demo
            oc start-build customermocker --from-dir=target/quarkus-app/ --follow -n quarkuscoffeeshop-demo
            oc new-app customermocker --name=customermocker --allow-missing-images -n quarkuscoffeeshop-demo
            oc set env deployment/customermocker JAVA_OPTS_APPEND="-Dquarkus.profile=prod" -n quarkuscoffeeshop-demo

            CONFIG_CORS_ORIGINS=$(oc get route homeoffice-ui -o jsonpath='{.spec.host}' -n quarkuscoffeeshop-demo)
            CONFIG_LOYALTY_STREAM_URL=$(oc get route homeoffice-ui -o jsonpath='{.spec.host}' -n quarkuscoffeeshop-demo)/dashboard/loyaltystream
            CONFIG_STREAM_URL=$(oc get route homeoffice-ui -o jsonpath='{.spec.host}' -n quarkuscoffeeshop-demo)/dashboard/stream
            CONFIG_REST_URL=$(oc get route homeoffice-ui -o jsonpath='{.spec.host}' -n quarkuscoffeeshop-demo)/graphql
            oc patch configmap coffeeshop-config -n quarkuscoffeeshop-demo -p "{\"data\":{\"CORS_ORIGINS\":\"http://$CONFIG_CORS_ORIGINS\"}}"
            oc patch configmap coffeeshop-config -n quarkuscoffeeshop-demo -p "{\"data\":{\"LOYALTY_STREAM_URL\":\"http://$CONFIG_LOYALTY_STREAM_URL\"}}"
            oc patch configmap coffeeshop-config -n quarkuscoffeeshop-demo -p "{\"data\":{\"STREAM_URL\":\"http://$CONFIG_STREAM_URL\"}}"
            oc patch configmap coffeeshop-config -n quarkuscoffeeshop-demo -p "{\"data\":{\"REST_URL\":\"http://$CONFIG_REST_URL\"}}"

            STREAM_URL=$(oc get configmap coffeeshop-config -n quarkuscoffeeshop-demo -o=jsonpath='{.data.STREAM_URL}')
            oc set env deployment/web STREAM_URL=$STREAM_URL -n quarkuscoffeeshop-demo
            LOYALTY_STREAM_URL=$(oc get configmap coffeeshop-config -n quarkuscoffeeshop-demo -o=jsonpath='{.data.LOYALTY_STREAM_URL}')
            oc set env deployment/web LOYALTY_STREAM_URL=$LOYALTY_STREAM_URL -n quarkuscoffeeshop-demo
            CORS_ORIGINS=$(oc get configmap coffeeshop-config -n quarkuscoffeeshop-demo -o=jsonpath='{.data.CORS_ORIGINS}')
            oc set env deployment/web CORS_ORIGINS=$CORS_ORIGINS -n quarkuscoffeeshop-demo
            STORE_ID=$(oc get configmap coffeeshop-config -n quarkuscoffeeshop-demo -o=jsonpath='{.data.STORE_ID}')
            oc set env deployment/web STORE_ID=$STORE_ID -n quarkuscoffeeshop-demo
      runAfter:
        - maven-run
      taskRef:
        name: push-app-task
      workspaces:
        - name: source
          workspace: shared-workspace
  workspaces:
  - name: shared-workspace
  - name: maven-settings