apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-and-push-quarkuscoffeeshop-customermocker
  labels:
    app: quarkuscoffeeshop-customermocker
  namespace: quarkuscoffeeshop-cicd
spec:
  params:
    - default: latest
      description: Image Tag Value
      name: IMAGE_TAG
      type: string
    - default: quay.io/quarkuscoffeeshop/quarkuscoffeeshop-customermocker
      name: quay-io-repository
      type: string
    - default: latest
      name: quay-io-image-tag-name
      type: string
    - default: webhook-secret
      description: Webhook secret name
      name: webhook-secret
      type: string
    - default: >-
        --patch={"spec":{"template":{"spec":{"containers":[{"name":"quarkuscoffeeshop-customermocker","image":"image-registry.openshift-image-registry.svc:5000/quarkuscoffeeshop-cicd/quarkuscoffeeshop-customermocker:CHANGEME_TO_TAG"}]}}}}
      description: CHANGEME_TO_TAG at the end of the string above
      name: PATCH_IMAGE
      type: string
    - default: quarkuscoffeeshop-demo
      description: Target Project
      name: target_project
      type: string
  resources:
    - name: app-git
      type: git
    - name: image
      type: image
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: 'https://github.com/quarkuscoffeeshop/quarkuscoffeeshop-customermocker'
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: maven-run
      params:
        - name: CONTEXT_DIR
          value: .
        - name: GOALS
          value:
            - '-DskipTests'
            - clean
            - package
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
    - name: build-java-app-image
      params:
        - name: CONTEXT
          value: .
        - name: DOCKERFILE
          value: src/main/docker/Dockerfile.jvm
        - name: IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/quarkuscoffeeshop-cicd/quarkuscoffeeshop-customermocker:$(params.IMAGE_TAG)
        - name: TLSVERIFY
          value: 'false'
      runAfter:
        - maven-run
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: tag-test-image
      params:
        - name: ARGS
          value:
            - tag
            - 'quarkuscoffeeshop-customermocker:$(params.IMAGE_TAG)'
            - 'quarkuscoffeeshop-customermocker:latest'
      runAfter:
        - build-java-app-image
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: push-to-test-env
      params:
        - name: ARGS
          value:
            - patch
            - deployment/quarkuscoffeeshop-customermocker
            - $(params.PATCH_IMAGE)
            - '-n'
            - $(params.target_project)
      runAfter:
        - tag-test-image
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: push-quarkuscoffeeshop-customermocker-image-to-quay
      params:
        - name: quay-io-repository
          value: $(params.quay-io-repository)
        - name: quay-io-image-tag-name
          value: $(params.quay-io-image-tag-name)
      resources:
        inputs:
          - name: image
            resource: image
      runAfter:
        - push-to-test-env
      taskRef:
        kind: Task
        name: push-quarkuscoffeeshop-customermocker-image-to-quay
  workspaces:
    - name: shared-workspace
    - name: maven-settings
