apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkuscoffeeshop-inventory
spec:
  destination:
    name: ''
    namespace: ' quarkuscoffeeshop-cicd'
    server: 'https://kubernetes.default.svc'
  source:
    path: quarkuscoffeeshop-inventory
    repoURL: %REPO_NAME%
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
