apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-push-quarkuscoffeeshop-inventory
  namespace: quarkuscoffeeshop-cicd
  labels:
    app: quarkuscoffeeshop-inventory
spec:
  params:
    - default: latest
      description: Image Tag Value
      name: IMAGE_TAG
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: 'https://github.com/nmushino/quarkuscoffeeshop-inventory'
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: maven-run
      params:
        - name: CONTEXT_DIR
          value: .
        - name: GOALS
          value:
            - clean
            - package
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
#    - name: build-java-app-image
#      params:
#        - name: CONTEXT
#          value: /workspace/source
#        - name: DOCKERFILE
#          value: /workspace/source/src/main/docker/Dockerfile.jvm
#        - name: IMAGE
#          value: >-
#            image-registry.openshift-image-registry.svc:5000/quarkuscoffeeshop-demo/quarkuscoffeeshop-inventory:$(params.IMAGE_TAG)
#      runAfter:
#        - maven-run
#      taskRef:
#        kind: ClusterTask
#        name: buildah
#      workspaces:
#        - name: source
#          workspace: shared-workspace
    - name: push-oc-apps
      params:
        - name: SCRIPT
          value: |
            #!/bin/bash
            set -e

            oc delete all -l app=inventory -n quarkuscoffeeshop-demo || true
            oc delete bc/inventory -n quarkuscoffeeshop-demo || true
            oc new-build --binary --name=inventory --image-stream=java:openjdk-17-ubi8 -n quarkuscoffeeshop-demo
            oc start-build inventory --from-dir=target/quarkus-app/ --follow -n quarkuscoffeeshop-demo
            oc new-app inventory --name=inventory --allow-missing-images -n quarkuscoffeeshop-demo
            oc set env deployment/inventory JAVA_OPTS_APPEND="-Dquarkus.profile=prod" -n quarkuscoffeeshop-demo

            PGSQL_URL=$(oc get configmap coffeeshop-config -n quarkuscoffeeshop-demo -o=jsonpath='{.data.PGSQL_URL}')
            oc set env deployment/inventory PGSQL_URL=$PGSQL_URL -n quarkuscoffeeshop-demo
            PGSQL_USER=$(oc get secret coffeeshopdb-pguser-coffeeshopadmin -n quarkuscoffeeshop-demo -o=jsonpath='{.data.user}' | base64 --decode)
            oc set env deployment/inventory PGSQL_USER=$PGSQL_USER -n quarkuscoffeeshop-demo
            PGSQL_PASS=$(oc get secret coffeeshopdb-pguser-coffeeshopadmin -n quarkuscoffeeshop-demo -o=jsonpath='{.data.password}' | base64 --decode)
            oc set env deployment/inventory PGSQL_PASS=$PGSQL_PASS -n quarkuscoffeeshop-demo

            KAFKA_URL=$(oc get configmap coffeeshop-config -n quarkuscoffeeshop-demo -o=jsonpath='{.data.KAFKA_BOOTSTRAP_URLS}')
            oc set env deployment/inventory KAFKA_BOOTSTRAP_URLS=$KAFKA_URL -n quarkuscoffeeshop-demo
            QUARKUS_LOG_LEVEL=$(oc get configmap coffeeshop-config -n quarkuscoffeeshop-demo -o=jsonpath='{.data.QUARKUS_LOG_LEVEL}')
            oc set env deployment/inventory QUARKUS_LOG_LEVEL=$QUARKUS_LOG_LEVEL -n quarkuscoffeeshop-demo
      runAfter:
        - maven-run
      taskRef:
        name: push-app-task
      workspaces:
        - name: source
          workspace: shared-workspace
  workspaces:
  - name: shared-workspace
  - name: maven-settings